export type GetEmailSettingResponse = {
  id: number;
  email_from_name: string | null;
  email_from_email: string | null;
  email_reply_email: string | null;
  custom_email_domain: string | null;
  custom_url_path_for_email: string | null;
  design_header_title_color: string | null;
  design_header_subtitle_color: string | null;
  design_btn_bg_color: string | null;
  design_btn_text_color: string | null;
  design_btn_sub_text_color: string | null;
  design_btn_radius: number | null;
  design_footer_text_color: string | null;
  design_footer_link_color: string | null;
  design_image: string | null;
  design_image_type: string | null;
  status: string;
  user_id: number;
  admin_ref: number;
  created_by: number;
  updated_by: number | null;
};
