export type UpdateReferralProgramRequest = {
  referral_friend_title: string;
  referral_friend_discount: string;
  referral_friend_is_minimum_cart_requirement: number;
  referral_friend_minimum_cart_value: number;
  referral_friend_apply_to: string;
  referral_friend_collection_id: number;
  referral_friend_purchase_type: string;
  referral_friend_expiry: number;
  referral_friend_icon: string;
  referral_friend_is_enabeled: number;
  referral_customer_points_amount: string;
  referral_customer_limit_count: number;
  referral_customer_limit_count_type: string;
  referral_customer_is_enabeled: number;
  referral_customer_description: string;
  referral_customer_icon: string;
  redirect_url: string;
  is_allowed_twitter_share: number;
  is_allowed_what_share: number;
  is_allowed_email_share: number;
  is_allowed_facebook_share: number;
  referral_user_link: string;
  referral_offer_cookie_Day: number;
  referral_offer_nco: number;
  status: string;
};
